In [1]:
import numpy as np

In [13]:
arr1 = np.array([[[1,2,3,4],[5,6,7,8]]])
arr2 = np.zeros((2,2,4))
arr3 = np.full((2,2,2), 7)
arr4 = np.ones((2,2))

In [14]:
print(arr1)
print(arr1.shape)

[[[1 2 3 4]
  [5 6 7 8]]]
(1, 2, 4)


In [12]:
print(arr2)
print(arr2.shape)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
(2, 2, 4)


In [9]:
print(arr3)


[[[7 7]
  [7 7]]

 [[7 7]
  [7 7]]]


In [10]:
print(arr4)

[[1. 1.]
 [1. 1.]]


In [32]:
arr = [10,20,30,40,50,60,70,80]
arrA = arr[0:8:2] # start : stop : number of skips
arrB = arr[:2] # start : end
arrC = arr[::3]   # each third element get skip
last = arr[-1]
reverse = arr[::-1]
print(reverse)


[80, 70, 60, 50, 40, 30, 20, 10]


In [34]:
list1 = np.random.rand(5)
list2 = np.random.rand(5)

In [ ]:
addition = np.add(list1, list2)
subtraction = np.subtract(list1, list2)
div = np.divide(list1, list2)
multiply = np.multiply(list1, list2)
dotProd = np.dot(list1, list2) # m1 x n1 and m2 x n2 and n1 must be equal to m2


In [ ]:
# SAPLEMM

sqrt = np.sqrt(25)
ab = np.abs(-1)
power = np.power(7,2)
log = np.log(2)
exp = np.exp(1)
mn = np.min(list1,list2)
mx = np.max(list1,list2)



In [43]:
arr5 = np.array([[1,2,3,4]])
print(arr5.shape)

# np.append(arr5, [2,3])
np.insert(arr5, 3, [5,5]) # array, index , values

(1, 4)


array([1, 2, 3, 5, 5, 4])

In [45]:
arr6 = np.random.rand(2,2,3)
print(arr6)

[[[0.2892365  0.28407168 0.93538289]
  [0.80545195 0.01150545 0.20074376]]

 [[0.59521678 0.03201014 0.26627482]
  [0.15913939 0.31450257 0.00706511]]]


In [49]:
np.delete(arr6, 0, axis=0)   # array, level, axis 1 means row 0 means columns 

array([[[0.59521678, 0.03201014, 0.26627482],
        [0.15913939, 0.31450257, 0.00706511]]])